import { useCallback, useEffect, useRef, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useBillingAccess, useBillingWriteGuard } from '@/lib/billingAccess'
export type MarketingKind='campaign'|'template'|'submission_log'
export type MarketingRecord={id:string;kind:MarketingKind;payload:any;customerId?:string;revision:number;createdAt:string}
type Row={id:string;kind:MarketingKind;payload:any;customer_id:string|null;revision:number;created_at:string}
const row=(value:Row):MarketingRecord=>({id:value.id,kind:value.kind,payload:value.payload,customerId:value.customer_id||undefined,revision:value.revision,createdAt:value.created_at})
export function useMarketingData(){const billing=useBillingAccess();const allow=useBillingWriteGuard();const [records,setRecords]=useState<MarketingRecord[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const request=useRef(0);const refresh=useCallback(async()=>{const id=++request.current;if(!supabase||!billing.companyAccountId){setRecords([]);setLoading(false);return}setRecords([]);setLoading(true);const {data,error}=await supabase.from('company_marketing_records').select('id,kind,payload,customer_id,revision,created_at').eq('company_account_id',billing.companyAccountId).order('created_at',{ascending:false});if(id!==request.current)return;if(error){setError(error.message);setLoading(false);return}setRecords((data||[]).map(row));setError(null);setLoading(false)},[billing.companyAccountId]);useEffect(()=>{void refresh()},[refresh]);const create=useCallback(async(kind:MarketingKind,payload:any,customerId?:string)=>{if(!allow('save marketing data'))return{ok:false as const,error:'Read-only account'};if(!supabase||!billing.companyAccountId)return{ok:false as const,error:'No active company account'};const id=payload.id||crypto.randomUUID();const {data,error}=await supabase.rpc('create_marketing_record',{p_id:id,p_company:billing.companyAccountId,p_kind:kind,p_customer:customerId||null,p_payload:{...payload,id}});if(error||!data)return{ok:false as const,error:error?.message||'Could not save marketing data'};const saved=row(data as Row);setRecords(items=>[saved,...items.filter(item=>item.id!==id)]);return{ok:true as const,record:saved}},[allow,billing.companyAccountId]);const update=useCallback(async(record:MarketingRecord,payload:any)=>{const {data,error}=await supabase.rpc('update_marketing_record',{p_id:record.id,p_company:billing.companyAccountId,p_payload:payload,p_revision:record.revision});if(error||!data)return{ok:false as const,error:error?.message||'Marketing record changed or no longer exists'};const saved=row(data as Row);setRecords(items=>items.map(item=>item.id===saved.id?saved:item));return{ok:true as const,record:saved}},[billing.companyAccountId]);const remove=useCallback(async(record:MarketingRecord)=>{const {error}=await supabase.rpc('delete_marketing_record',{p_id:record.id,p_company:billing.companyAccountId,p_revision:record.revision});if(error)return{ok:false as const,error:error.message};setRecords(items=>items.filter(item=>item.id!==record.id));return{ok:true as const}},[billing.companyAccountId]);return{records,loading,error,refresh,create,update,remove}}

const LEGACY_KEYS: Record<MarketingKind, string> = { campaign: 'marketing.campaigns.v1', template: 'marketing.templates.v1', submission_log: 'marketing.template.sends.v1' }
const legacyRecords = (kind: MarketingKind) => { try { const parsed = JSON.parse(localStorage.getItem(LEGACY_KEYS[kind]) || '[]'); return Array.isArray(parsed) ? parsed : [] } catch { return [] } }
const withoutCredentials = (payload: any) => { const { apiKey, api_key, token, accessToken, credentials, ...safe } = payload || {}; return safe }

export function useCompanyMarketingData() {
	const base = useMarketingData(); const latest = useRef<MarketingRecord[]>([])
	useEffect(() => { latest.current = base.records }, [base.records])
	const byKind = (kind: MarketingKind) => base.records.filter(record => record.kind === kind)
	const save = useCallback(async (kind: Exclude<MarketingKind, 'submission_log'>, payload: any, customerId?: string) => base.create(kind, withoutCredentials(payload), customerId), [base.create])
	const update = useCallback(async (record: MarketingRecord, payload: any) => base.update(record, withoutCredentials(payload)), [base.update])
	const recordSubmission = useCallback(async (input: { id?: string; campaignId?: string; templateId?: string; customerId?: string; channel: string; providerAccepted: boolean; providerOutcome?: string; recipientCount: number }) => {
		const outcome = input.providerAccepted ? 'accepted' : 'failed'
		const result = await base.create('submission_log', { ...input, id: input.id || crypto.randomUUID(), outcome, deliveryStatus: 'not-confirmed' }, input.customerId)
		return result.ok ? { ok: true as const, providerAccepted: input.providerAccepted, log: result.record } : { ok: false as const, providerAccepted: input.providerAccepted, recordingError: result.error }
	}, [base.create])
	const importLegacy = useCallback(async () => { let imported = 0, skipped = 0; const failures: Array<{ id: string; reason: string }> = []; for (const kind of Object.keys(LEGACY_KEYS) as MarketingKind[]) for (const item of legacyRecords(kind)) { const id = String(item?.id || ''); if (!id || latest.current.some(record => record.id === id)) { skipped++; continue } const result = await base.create(kind, withoutCredentials({ ...item, id }), item.customerId); if (result.ok) { imported++; latest.current = [result.record, ...latest.current] } else if (/duplicate|unique/i.test(result.error)) skipped++; else failures.push({ id, reason: result.error }) } return { ok: true as const, imported, skipped, failures } }, [base.create])
	return { ...base, campaigns: byKind('campaign'), templates: byKind('template'), submissionLogs: byKind('submission_log'), save, update, recordSubmission, importLegacy, legacyCount: (Object.keys(LEGACY_KEYS) as MarketingKind[]).reduce((count, kind) => count + legacyRecords(kind).length, 0) }
}
