import React from 'react'
import { renderHook, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { BillingAccessProvider, type BillingAccess } from '@/lib/billingAccess'
const { pending, supabaseMock }=vi.hoisted(()=>{const pending=new Map<string,((value:any)=>void)[]>();const supabaseMock:any={from:()=>{let company='';const q:any={select:()=>q,eq:(_:string,value:string)=>{company=value;return q},order:()=>new Promise(resolve=>{const list=pending.get(company)||[];list.push(resolve);pending.set(company,list)})};return q},rpc:vi.fn(async(name:string,args:any)=>name==='create_marketing_record'?{data:{id:args.p_id,kind:args.p_kind,payload:args.p_payload,customer_id:args.p_customer,revision:1,created_at:'2026-09-15T00:00:00Z'},error:null}:{error:{message:'Marketing record changed or no longer exists'}})};return{pending,supabaseMock}})
vi.mock('@/lib/supabase',()=>({supabase:supabaseMock}))
import { useCompanyMarketingData } from '@/lib/marketingData'
let company='marketing-a';const access=(companyAccountId:string):BillingAccess=>({readOnly:false,hasFullAccess:true,canUsePremiumFeatures:true,isFounder:false,isPastDue:false,statusMessage:'',companyAccountId,companyName:companyAccountId,userId:'user'})
const Wrapper=({children}:{children:React.ReactNode})=><BillingAccessProvider value={access(company)}>{children}</BillingAccessProvider>
beforeEach(()=>{company='marketing-a';pending.clear();localStorage.clear();vi.clearAllMocks();vi.stubGlobal('fetch',vi.fn())})
describe('Block 6F marketing data hook',()=>{it('clears A and ignores a late A response after changing company',async()=>{const {result,rerender}=renderHook(()=>useCompanyMarketingData(),{wrapper:Wrapper});await waitFor(()=>expect(pending.get('marketing-a')).toHaveLength(1));company='marketing-b';rerender();await waitFor(()=>expect(pending.get('marketing-b')).toHaveLength(1));expect(result.current.records).toEqual([]);pending.get('marketing-b')![0]({data:[{id:'b',kind:'campaign',payload:{name:'B'},customer_id:null,revision:1,created_at:'2026-09-15T00:00:00Z'}],error:null});await waitFor(()=>expect(result.current.campaigns[0]?.id).toBe('b'));pending.get('marketing-a')![0]({data:[{id:'a',kind:'campaign',payload:{name:'A'},customer_id:null,revision:1,created_at:'2026-09-15T00:00:00Z'}],error:null});await new Promise(resolve=>setTimeout(resolve,0));expect(result.current.records.map(record=>record.id)).toEqual(['b'])})
it('preserves legacy source, imports IDs once, and makes no provider calls',async()=>{const {result}=renderHook(()=>useCompanyMarketingData(),{wrapper:Wrapper});await waitFor(()=>expect(pending.get('marketing-a')).toHaveLength(1));pending.get('marketing-a')![0]({data:[],error:null});const source='[{"id":"legacy-campaign","name":"Legacy"}]';localStorage.setItem('marketing.campaigns.v1',source);const first=await result.current.importLegacy();const second=await result.current.importLegacy();expect(first.imported).toBe(1);expect(second.skipped).toBe(1);expect(localStorage.getItem('marketing.campaigns.v1')).toBe(source);expect(global.fetch).not.toHaveBeenCalled()})})
