import React from 'react'
import { renderHook, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { BillingAccessProvider, type BillingAccess } from '@/lib/billingAccess'
const { pending, rows, supabaseMock } = vi.hoisted(() => {
	const pending = new Map<string, ((value: any) => void)[]>(); const rows = new Map<string, any[]>();
	const supabaseMock: any = { from: () => { let company = ''; let customer = ''; const query: any = { select: () => query, eq: (field: string, value: string) => { if (field === 'company_account_id') company = value; if (field === 'customer_id') customer = value; return query; }, order: () => new Promise(resolve => { const key = `${company}:${customer}`; const requests = pending.get(key) || []; requests.push(resolve as any); pending.set(key, requests); }) }; return query; }, rpc: vi.fn(async (name: string, args: any) => { const key = `${args.p_company}:${args.p_customer || 'customer-a'}`; const existing = rows.get(key) || []; if (name === 'create_company_preset') { if (existing.some(item => item.id === args.p_id)) return { data: null, error: { message: 'duplicate' } }; const saved = { id: args.p_id, name: args.p_name, state: args.p_state, created_at: '2026-09-15T00:00:00.000Z', revision: 1 }; rows.set(key, [saved, ...existing]); return { data: saved, error: null }; } if (name === 'update_company_preset') return { data: null, error: { message: 'Preset changed or no longer exists' } }; return { error: null }; }) };
	return { pending, rows, supabaseMock };
})
vi.mock('@/lib/supabase',()=>({supabase:supabaseMock}))
import { useCompanyPresets } from '@/lib/presets'
let company='company-a';let customer='customer-a';const access=(companyAccountId:string):BillingAccess=>({readOnly:false,hasFullAccess:true,canUsePremiumFeatures:true,isFounder:false,isPastDue:false,statusMessage:'',companyAccountId,companyName:companyAccountId,userId:'user'})
const Wrapper=({children}:{children:React.ReactNode})=><BillingAccessProvider value={access(company)}>{children}</BillingAccessProvider>
beforeEach(()=>{company='company-a';customer='customer-a';pending.clear();rows.clear();localStorage.clear();vi.clearAllMocks()})
describe('Block 6E company presets hook',()=>{it('clears company/customer changes and ignores late responses',async()=>{const {result,rerender}=renderHook(()=>useCompanyPresets(customer),{wrapper:Wrapper});await waitFor(()=>expect(pending.get('company-a:customer-a')).toHaveLength(1));company='company-b';customer='customer-b';rerender();await waitFor(()=>expect(pending.get('company-b:customer-b')).toHaveLength(1));expect(result.current.presets).toEqual([]);pending.get('company-b:customer-b')![0]({data:[{id:'b',name:'B',state:{frame:{id:'f-b'}},created_at:'2026-09-15T00:00:00.000Z',revision:1}],error:null});await waitFor(()=>expect(result.current.presets[0]?.id).toBe('b'));pending.get('company-a:customer-a')![0]({data:[{id:'a',name:'A',state:{},created_at:'2026-09-15T00:00:00.000Z',revision:1}],error:null});await new Promise(resolve=>setTimeout(resolve,0));expect(result.current.presets.map(p=>p.id)).toEqual(['b'])})
it('returns failed writes without phantom data and imports legacy IDs without changing source',async()=>{const {result}=renderHook(()=>useCompanyPresets(customer),{wrapper:Wrapper});await waitFor(()=>expect(pending.get('company-a:customer-a')).toHaveLength(1));pending.get('company-a:customer-a')![0]({data:[],error:null});const failed=await result.current.update({id:'missing',name:'Missing',state:{},createdAt:0,revision:1});expect(failed.ok).toBe(false);expect(result.current.presets).toEqual([]);const raw='[{"id":"legacy","name":"Legacy","createdAt":4,"state":{"frame":{"id":"frame-a"}}}]';localStorage.setItem('frameit_presets_v1_customer-a',raw);const first=await result.current.importLegacy();const second=await result.current.importLegacy();expect(first).toMatchObject({imported:1,skipped:0});expect(second).toMatchObject({imported:0,skipped:1});expect(rows.get('company-a:customer-a')![0].id).toBe('legacy');expect(localStorage.getItem('frameit_presets_v1_customer-a')).toBe(raw)})})
