import React from 'react'
import { renderHook, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { BillingAccessProvider, type BillingAccess } from '@/lib/billingAccess'
const { pending, supabaseMock }=vi.hoisted(()=>{const pending=new Map<string,((value:any)=>void)[]>();const supabaseMock:any={from:()=>{let company='';const q:any={select:()=>q,eq:(_:string,value:string)=>{company=value;return q},order:()=>new Promise(resolve=>{const list=pending.get(company)||[];list.push(resolve);pending.set(company,list)})};return q}};return {pending,supabaseMock}})
vi.mock('@/lib/supabase',()=>({supabase:supabaseMock,getAccessToken:vi.fn()}))
import { useCompanyMembers } from '@/lib/companyMembers'
let company='member-a';const access=(companyAccountId:string):BillingAccess=>({readOnly:false,hasFullAccess:true,canUsePremiumFeatures:true,isFounder:false,isPastDue:false,statusMessage:'',companyAccountId,companyName:companyAccountId,userId:'user'})
const Wrapper=({children}:{children:React.ReactNode})=><BillingAccessProvider value={access(company)}>{children}</BillingAccessProvider>
beforeEach(()=>{company='member-a';pending.clear()})
describe('Block 6D canonical company members',()=>{it('clears A and ignores a late response after switching to B',async()=>{const {result,rerender}=renderHook(()=>useCompanyMembers(),{wrapper:Wrapper});await waitFor(()=>expect(pending.get('member-a')).toHaveLength(1));company='member-b';rerender();await waitFor(()=>expect(pending.get('member-b')).toHaveLength(1));expect(result.current.members).toEqual([]);pending.get('member-b')![0]({data:[{id:'b-active',company_account_id:'member-b',user_id:'b-user',email:'b@test.local',full_name:'B',phone:null,role:'staff',status:'active',invited_at:'',joined_at:null,last_invite_sent_at:null},{id:'b-inactive',company_account_id:'member-b',user_id:'b-old',email:'old@test.local',full_name:'Old',phone:null,role:'staff',status:'inactive',invited_at:'',joined_at:null,last_invite_sent_at:null}],error:null});await waitFor(()=>expect(result.current.members.map(member=>member.user_id)).toEqual(['b-user','b-old']));pending.get('member-a')![0]({data:[{id:'a',company_account_id:'member-a',user_id:'a-user',email:'a@test.local',full_name:'A',phone:null,role:'staff',status:'active',invited_at:'',joined_at:null,last_invite_sent_at:null}],error:null});await new Promise(resolve=>setTimeout(resolve,0));expect(result.current.members.map(member=>member.user_id)).toEqual(['b-user','b-old'])})})
