import React from 'react'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const hook = vi.hoisted(() => ({ presets: [] as any[], loading:false, error:null as string|null, legacyCount:0, save:vi.fn(), remove:vi.fn(), importLegacy:vi.fn() }))
vi.mock('@/lib/presets',()=>({useCompanyPresets:()=>hook}))
import PresetControls from '@/components/PresetControls'
const state={frame:{id:'frame-a'},art:{widthCm:40}}
const base={companyName:'Company A',customerKey:'customer-a',hasSavedCustomer:true,ensureCustomerId:vi.fn(async()=> 'customer-a'),currentState:state,onApply:vi.fn()}
const openSave=()=>{fireEvent.click(screen.getByRole('button',{name:'Save preset'}));fireEvent.click(screen.getAllByRole('button',{name:'Save preset'})[1])}
afterEach(cleanup)
beforeEach(()=>{vi.clearAllMocks();hook.presets=[];hook.loading=false;hook.error=null;hook.legacyCount=0;hook.save.mockResolvedValue({ok:true,preset:{id:'saved',name:'Saved',state,createdAt:1,revision:1}});hook.remove.mockResolvedValue({ok:true});hook.importLegacy.mockResolvedValue({ok:true,imported:1,skipped:0,failures:[]});vi.stubGlobal('prompt',vi.fn(()=> 'Saved'));vi.stubGlobal('confirm',vi.fn(()=>true))})
describe('Block 6E preset controls',()=>{
 it('saves, remounts, and applies the persisted configuration',async()=>{const {unmount}=render(<PresetControls {...base}/>);openSave();await waitFor(()=>expect(hook.save).toHaveBeenCalledWith({id:'',name:'Saved',state}));expect(screen.getByRole('status').textContent).toBe('Preset saved.');unmount();hook.presets=[{id:'saved',name:'Saved',state,createdAt:1,revision:1}];render(<PresetControls {...base}/>);fireEvent.click(screen.getByRole('button',{name:'Load'}));expect(base.onApply).toHaveBeenCalledWith(hook.presets[0])})
 it('reports save and delete failures without success feedback',async()=>{hook.save.mockResolvedValue({ok:false,error:'Save failed'});hook.presets=[{id:'saved',name:'Saved',state,createdAt:1,revision:1}];hook.remove.mockResolvedValue({ok:false,error:'Preset changed or no longer exists'});render(<PresetControls {...base}/>);openSave();await waitFor(()=>expect(screen.getByRole('status').textContent).toBe('Save failed'));fireEvent.click(screen.getByRole('button',{name:'Delete'}));await waitFor(()=>expect(screen.getByRole('status').textContent).toBe('Preset changed or no longer exists'));expect(screen.queryByText('Preset deleted.')).toBeNull()})
 it('suppresses late save feedback after a scope switch',async()=>{let resolve:any;hook.save.mockReturnValue(new Promise(done=>{resolve=done}));const {rerender}=render(<PresetControls {...base}/>);openSave();rerender(<PresetControls {...base} companyName="Company B" customerKey="customer-b"/>);resolve({ok:true,preset:{id:'old',name:'Old',state,createdAt:1}});await new Promise(done=>setTimeout(done,0));expect(screen.queryByRole('status')).toBeNull();expect(base.onApply).not.toHaveBeenCalled()})
 it('confirms scoped legacy import and reports partial failures',async()=>{hook.legacyCount=2;hook.importLegacy.mockResolvedValue({ok:true,imported:1,skipped:0,failures:[{id:'bad',reason:'bad'}]});render(<PresetControls {...base}/>);fireEvent.click(screen.getByRole('button',{name:'Import legacy presets'}));expect(window.confirm).toHaveBeenCalledWith('Import 2 legacy presets into Company A for customer customer-a? Original browser data will be preserved.');await waitFor(()=>expect(screen.getByRole('status').textContent).toBe('1 imported, 0 already imported. 1 failed.'))})
 it('does not create a preset when customer persistence fails and requires a second save after creation',async()=>{const ensure=vi.fn().mockResolvedValueOnce('').mockResolvedValueOnce('customer-a');render(<PresetControls {...base} hasSavedCustomer={false} ensureCustomerId={ensure}/>);openSave();await waitFor(()=>expect(screen.getByRole('status').textContent).toBe('Save the customer before saving a preset.'));expect(hook.save).not.toHaveBeenCalled();openSave();await waitFor(()=>expect(screen.getByRole('status').textContent).toBe('Customer saved. Save the preset again now that it is assigned to this customer.'));expect(hook.save).not.toHaveBeenCalled()})
})
